import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#4f4d7f',
        'on-tertiary-fixed-variant': '#503c76',
        'on-surface': '#e5e1e6',
        'on-secondary-fixed': '#231a00',
        'primary-container': '#c4c1fb',
        'secondary-fixed': '#ffe087',
        'on-surface-variant': '#c8c5d0',
        'on-tertiary-container': '#5c4883',
        'tertiary-fixed-dim': '#d3bbff',
        'inverse-on-surface': '#313034',
        'neutral-champagne': '#e6e3d3',
        'on-secondary-container': '#342800',
        'secondary-fixed-dim': '#e9c349',
        'secondary-container': '#ae8d10',
        'on-tertiary': '#39255e',
        'surface-container-lowest': '#0e0e11',
        'surface-dim': '#0a0a0c',
        'background': '#0a0a0c',
        'surface-bright': '#3a393c',
        'on-tertiary-fixed': '#230d48',
        'tertiary-container': '#d3bbff',
        'surface-container-highest': '#353438',
        'tertiary-fixed': '#ebddff',
        'on-secondary': '#3c2f00',
        'error': '#ffb4ab',
        'surface-container-high': '#2a292d',
        'surface-tint': '#c4c1fb',
        'error-container': '#93000a',
        'secondary': '#e9c349',
        'primary-fixed-dim': '#c4c1fb',
        'surface-container': '#18181b',
        'surface-base': '#0a0a0a',
        'on-primary-fixed-variant': '#434172',
        'surface-variant': '#1c1c1f',
        'surface': '#0a0a0c',
        'on-primary': '#2c2b5a',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#111114',
        'on-error': '#690005',
        'tertiary': '#ebdcff',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-plum': '#d3bbff',
        'primary-fixed': '#e3dfff',
        'primary': '#e3dfff',
        'inverse-surface': '#e5e1e6',
        'outline': '#4a4a4f',
        'inverse-primary': '#5b598c',
        'on-background': '#e5e1e6',
        'outline-variant': '#353438',
        'on-primary-fixed': '#171544',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
        sm: '0px',
        md: '0px',
        none: '0px',
      },
      spacing: {
        'stack-sm': '8px',
        'overlap-offset': '-48px',
        'stack-md': '16px',
        'margin-mobile': '24px',
        'gutter': '32px',
        'section-padding': '120px',
        'stack-lg': '48px',
        'container-max': '1200px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'body-lg': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-xl': ['Bodoni Moda', 'Georgia', 'serif'],
        'body-md': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-md': ['Bodoni Moda', 'Georgia', 'serif'],
        'headline-lg': ['Bodoni Moda', 'Georgia', 'serif'],
        'headline-md-mobile': ['Bodoni Moda', 'Georgia', 'serif'],
        'label-md': ['Metrophobic', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['20px', { lineHeight: '32px', fontWeight: '400' }],
        'headline-xl': ['110px', { lineHeight: '95px', letterSpacing: '-0.04em', fontWeight: '200' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '300' }],
        'headline-md': ['36px', { lineHeight: '44px', fontWeight: '300' }],
        'headline-lg': ['56px', { lineHeight: '60px', letterSpacing: '-0.01em', fontWeight: '300' }],
        'headline-md-mobile': ['32px', { lineHeight: '40px', fontWeight: '300' }],
        'label-md': ['11px', { lineHeight: '18px', letterSpacing: '0.25em', fontWeight: '400' }],
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
}

export default config
